/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once this code is regenerated.
 * 
 * @generated by codegen project: GenerateModuleH.js
*/

#include "NativeCxxModuleExampleCxxSpec.h"

using namespace rnoh;
using namespace facebook;
using namespace react;

bool NativeCxxModuleExampleCxxSpecJSI::getBool(jsi::Runtime &rt, bool arg) { return arg; }

int32_t NativeCxxModuleExampleCxxSpecJSI::getEnum(jsi::Runtime &rt, int32_t arg) { return arg; }

double NativeCxxModuleExampleCxxSpecJSI::getNumber(jsi::Runtime &rt, double arg) {return arg;}

void NativeCxxModuleExampleCxxSpecJSI::voidFunc(jsi::Runtime &rt) {
    // Nothing to do
}

static jsi::Value __hostFunction_NativeCxxModuleExampleCxxSpecJSI_getBool(jsi::Runtime &rt,
                                                                          react::TurboModule &turboModule,
                                                                          const jsi::Value *args, size_t count) {
    return static_cast<NativeCxxModuleExampleCxxSpecJSI *>(&turboModule)->getBool(rt, args[0].asBool());
}

static jsi::Value __hostFunction_NativeCxxModuleExampleCxxSpecJSI_getEnum(jsi::Runtime &rt,
                                                                        react::TurboModule &turboModule,
                                                                        const jsi::Value *args, size_t count) {
    return static_cast<NativeCxxModuleExampleCxxSpecJSI *>(&turboModule)->getEnum(rt, args[0].asNumber());
}

static jsi::Value __hostFunction_NativeCxxModuleExampleCxxSpecJSI_getNumber(jsi::Runtime &rt,
                                                                        react::TurboModule &turboModule,
                                                                        const jsi::Value *args, size_t count) {
    return static_cast<NativeCxxModuleExampleCxxSpecJSI *>(&turboModule)->getNumber(rt, args[0].asNumber());
}

static jsi::Value __hostFunction_NativeCxxModuleExampleCxxSpecJSI_voidFunc(jsi::Runtime &rt,
                                                                        react::TurboModule &turboModule,
                                                                        const jsi::Value *args, size_t count) {
    static_cast<NativeCxxModuleExampleCxxSpecJSI *>(&turboModule)->voidFunc(rt);
    return jsi::Value::undefined();
}

NativeCxxModuleExampleCxxSpecJSI::NativeCxxModuleExampleCxxSpecJSI(const ArkTSTurboModule::Context ctx,
                                                                  const std::string name)
    : ArkTSTurboModule(ctx, name) {
    methodMap_["getBool"] = MethodMetadata{1, __hostFunction_NativeCxxModuleExampleCxxSpecJSI_getBool};
    methodMap_["getEnum"] = MethodMetadata{1, __hostFunction_NativeCxxModuleExampleCxxSpecJSI_getEnum};
    methodMap_["getNumber"] = MethodMetadata{1, __hostFunction_NativeCxxModuleExampleCxxSpecJSI_getNumber};
    methodMap_["voidFunc"] = MethodMetadata{0, __hostFunction_NativeCxxModuleExampleCxxSpecJSI_voidFunc};
}